### ISSUE TITLE
¿Se ha perdido el código del chonizador?

### ISSUE THREAD

**Issue by coriumalpha** [chevismo/chevismo.com#1]
Revisando en Google todos los enlaces al clásico chonizador me redirigen a la web chevismo.com, por lo que deduzco que este repositorio debería contener el código original del chonizador.
¿Saben algo al respecto?

Un saludo,
Gracias.

**Comment by aurbano** [comment]
Lo tengo pero no esta subido a ningun sitio ahora mismo - supongo que podria dedicar una tarde a pasarlo a JS y ponerlo online la verdad... 🤔

**Comment by coriumalpha** [comment]
Aquí en España se convirtió en una valiosísima pieza de historia, especialmente durante la época en la que existió Tuenti.
La verdad es que sería un lujo poder contar con el código original, aunque sólo sea por poder admirar su esencia pura.
¿Podrías subirlo a algún lugar o mandarme un MD con el contenido? Siento una inmensa curiosidad hacia cómo funcionaba tan curiosa herramienta.
Gracias y felicidades por el proyecto :)
